# Generated by Django 5.1.5 on 2025-01-29 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheetdata',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='spreadsheetdata',
            name='column2',
        ),
        migrations.RemoveField(
            model_name='spreadsheetdata',
            name='column3',
        ),
        migrations.RemoveField(
            model_name='spreadsheetdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='CHANGE_OI',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='CLOSE_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='DATE',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='EXPIRY_DATE',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='HIGH_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='LAST_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='LOW_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='OPEN_INTEREST',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='OPEN_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='PREMIUM_VALUE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='SETTLE_PRICE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='VALUE',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='spreadsheetdata',
            name='VOLUME',
            field=models.FloatField(null=True),
        ),
    ]
