# Generated by Django 5.1.5 on 2025-01-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0002_remove_spreadsheetdata_column1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('option_type', models.CharField(max_length=10)),
                ('strike_price', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('settle_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('value', models.CharField(max_length=255)),
                ('premium_value', models.CharField(max_length=255)),
                ('open_interest', models.BigIntegerField()),
                ('change_in_oi', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SpreadsheetData',
        ),
    ]
